// Generated by GAS WebApp Builder | Created by @tghbdn

/**
 * Endpoint utama Web App untuk merender index.html
 */
function doGet(e) {
    return HtmlService.createTemplateFromFile('Index')
        .evaluate()
        .setTitle('KasirQu - Sistem Kasir POS & Inventaris Modern')
        .addMetaTag('viewport', 'width=device-width, initial-scale=1')
        .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

/**
 * Setup basis data Google Sheet & pengguna admin bawaan
 */
function setupDatabase() {
    const ss = SpreadsheetApp.getActiveSpreadsheet();

    // 1. Sheet Users
    let usersSheet = ss.getSheetByName('Users');
    if (!usersSheet) {
        usersSheet = ss.insertSheet('Users');
        usersSheet.appendRow(['Username', 'PasswordHash', 'Fullname', 'Role']);
    }

    // Pastikan setidaknya ada user admin bawaan
    if (usersSheet.getLastRow() <= 1) {
        // Default password 'Admin@2026' di-hash SHA-256
        const defaultHash = hashPassword('Admin@2026');
        usersSheet.appendRow(['admin', defaultHash, 'Administrator Kasir', 'Admin']);
        usersSheet.appendRow(['staff', hashPassword('Admin@2026'), 'Kasir Toko', 'Staff']);
    }

    // 2. Sheet Products
    let productsSheet = ss.getSheetByName('Products');
    if (!productsSheet) {
        productsSheet = ss.insertSheet('Products');
        productsSheet.appendRow(['ID', 'Name', 'Price', 'Category', 'Stock', 'Emoji']);
        // Seed default produk
        productsSheet.appendRow(['1', 'Nasi Goreng Spesial', '25000', 'Makanan', '30', '🍳']);
        productsSheet.appendRow(['2', 'Mie Goreng Jawa', '22000', 'Makanan', '25', '🍜']);
        productsSheet.appendRow(['3', 'Ayam Bakar Madu', '28000', 'Makanan', '15', '🍗']);
        productsSheet.appendRow(['4', 'Es Teh Manis', '5000', 'Minuman', '100', '🥤']);
        productsSheet.appendRow(['5', 'Kopi Susu Gula Aren', '18000', 'Minuman', '50', '☕']);
    }

    // 3. Sheet Transactions
    let txSheet = ss.getSheetByName('Transactions');
    if (!txSheet) {
        txSheet = ss.insertSheet('Transactions');
        txSheet.appendRow(['ID', 'Date', 'ItemsJSON', 'Subtotal', 'DiscountPercent', 'DiscountAmount', 'TaxAmount', 'GrandTotal', 'Method', 'CashPaid', 'Change']);
    }

    // 4. Sheet StockIn
    let stockInSheet = ss.getSheetByName('StockIn');
    if (!stockInSheet) {
        stockInSheet = ss.insertSheet('StockIn');
        stockInSheet.appendRow(['ID', 'Date', 'Supplier', 'ItemsJSON', 'TotalCost']);
    }

    // 5. Sheet AuditLog
    let logSheet = ss.getSheetByName('AuditLog');
    if (!logSheet) {
        logSheet = ss.insertSheet('AuditLog');
        logSheet.appendRow(['Timestamp', 'Username', 'Action', 'Detail']);
    }

    return "Database berhasil disiapkan! Gunakan user: admin / password: Admin@2026";
}

/**
 * Enkripsi password menggunakan Utilities SHA-256
 */
function hashPassword(password) {
    var digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password, Utilities.Charset.UTF_8);
    var hexString = '';
    for (var i = 0; i < digest.length; i++) {
        var byteValue = digest[i];
        if (byteValue < 0) byteValue += 256;
        var byteString = byteValue.toString(16);
        if (byteString.length == 1) byteString = '0' + byteString;
        hexString += byteString;
    }
    return hexString;
}

/**
 * Logika Login Pengguna dengan Rate Limit Keamanan
 */
function loginUser(username, password) {
    const normUser = String(username).trim().toLowerCase();

    // Cek Rate Limit
    const lockCheck = checkLoginRateLimit(normUser);
    if (lockCheck.locked) {
        return { success: false, message: "Terlalu banyak percobaan masuk! Akun terkunci selama " + lockCheck.remaining + " menit lagi." };
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('Users');
    if (!sheet) return { success: false, message: "Sheet Users belum dikonfigurasi. Hubungi Admin." };

    const values = sheet.getDataRange().getValues();
    const passHash = hashPassword(password);

    for (let i = 1; i < values.length; i++) {
        const rowUser = String(values[i][0]).toLowerCase();
        const rowPass = String(values[i][1]);

        if (rowUser === normUser && rowPass === passHash) {
            // Login Sukses
            clearLoginFailures(normUser);
            const token = generateSessionToken(normUser);

            const userData = {
                username: values[i][0],
                fullname: values[i][2],
                role: values[i][3]
            };

            logAction(normUser, "LOGIN", "Berhasil masuk ke aplikasi.");
            return { success: true, user: userData, token: token };
        }
    }

    // Login Gagal
    recordLoginFailure(normUser);
    return { success: false, message: "Username atau Password salah." };
}

// --- MANAJEMEN SESI CACHE SERVICE ---
function generateSessionToken(username) {
    const token = Utilities.getUuid();
    const cache = CacheService.getScriptCache();
    // Durasi sesi 8 Jam (28800 detik)
    cache.put(token, username, 28800);
    return token;
}

function validateSession(token) {
    if (!token) return { valid: false, message: "Sesi tidak valid." };
    const cache = CacheService.getScriptCache();
    const cachedUsername = cache.get(token);

    if (cachedUsername) {
        return { valid: true, username: cachedUsername };
    }
    return { valid: false, message: "Sesi Anda telah kedaluwarsa." };
}

function destroySession(token) {
    if (!token) return { success: true };
    const cache = CacheService.getScriptCache();
    cache.remove(token);
    return { success: true };
}

// --- RATE LIMIT SECURITY CONTROLLER ---
function checkLoginRateLimit(username) {
    const cache = CacheService.getScriptCache();
    const failCount = cache.get("fail_" + username);
    const lockTimestamp = cache.get("lock_" + username);

    if (lockTimestamp) {
        const remainingMillis = parseInt(lockTimestamp) - Date.now();
        if (remainingMillis > 0) {
            const remainingMinutes = Math.ceil(remainingMillis / 60000);
            return { locked: true, remaining: remainingMinutes };
        } else {
            cache.remove("lock_" + username);
            cache.remove("fail_" + username);
        }
    }
    return { locked: false };
}

function recordLoginFailure(username) {
    const cache = CacheService.getScriptCache();
    let failCount = parseInt(cache.get("fail_" + username) || "0") + 1;

    if (failCount >= 5) {
        // Blokir 15 Menit (900000 ms)
        const lockUntil = Date.now() + 900000;
        cache.put("lock_" + username, String(lockUntil), 900);
        cache.remove("fail_" + username);
    } else {
        cache.put("fail_" + username, String(failCount), 900);
    }
}

function clearLoginFailures(username) {
    const cache = CacheService.getScriptCache();
    cache.remove("fail_" + username);
    cache.remove("lock_" + username);
}

// --- AUDIT LOGS WRITER ---
function logAction(username, action, detail) {
    try {
        const ss = SpreadsheetApp.getActiveSpreadsheet();
        const sheet = ss.getSheetByName('AuditLog');
        if (sheet) {
            sheet.appendRow([new Date(), username, action, detail]);
        }
    } catch (e) {
        Logger.log("Gagal menulis log: " + e.message);
    }
}

// ================= DATA CONTROLLERS & SYNC =================
/**
 * Ambil seluruh muatan basis data utama sekaligus
 */
function getInitialData(token) {
    const session = validateSession(token);
    if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

    const ss = SpreadsheetApp.getActiveSpreadsheet();

    // Ambil Data Produk
    const products = [];
    const prodSheet = ss.getSheetByName('Products');
    if (prodSheet) {
        const prodValues = prodSheet.getDataRange().getValues();
        for (let i = 1; i < prodValues.length; i++) {
            products.push({
                id: parseInt(prodValues[i][0]),
                name: String(prodValues[i][1]),
                price: parseFloat(prodValues[i][2]),
                category: String(prodValues[i][3]),
                stock: parseInt(prodValues[i][4]),
                emoji: String(prodValues[i][5])
            });
        }
    }

    // Ambil Data Penjualan
    const transactions = [];
    const txSheet = ss.getSheetByName('Transactions');
    if (txSheet) {
        const txValues = txSheet.getDataRange().getValues();
        for (let i = txValues.length - 1; i >= 1; i--) {
            transactions.push({
                id: String(txValues[i][0]),
                date: String(txValues[i][1]),
                items: JSON.parse(txValues[i][2]),
                values: {
                    subtotal: parseFloat(txValues[i][3]),
                    discountPercent: parseFloat(txValues[i][4]),
                    discountAmount: parseFloat(txValues[i][5]),
                    taxAmount: parseFloat(txValues[i][6]),
                    grandTotal: parseFloat(txValues[i][7])
                },
                method: String(txValues[i][8]),
                cashPaid: parseFloat(txValues[i][9]),
                change: parseFloat(txValues[i][10])
            });
        }
    }

    // Ambil Data Stok Masuk
    const stockInTransactions = [];
    const stSheet = ss.getSheetByName('StockIn');
    if (stSheet) {
        const stValues = stSheet.getDataRange().getValues();
        for (let i = stValues.length - 1; i >= 1; i--) {
            stockInTransactions.push({
                id: String(stValues[i][0]),
                date: String(stValues[i][1]),
                supplier: String(stValues[i][2]),
                items: JSON.parse(stValues[i][3]),
                totalCost: parseFloat(stValues[i][4])
            });
        }
    }

    return { success: true, products, transactions, stockInTransactions };
}

/**
 * Menyimpan Produk baru atau Memperbarui produk lama (Lock Service Enabled)
 */
function saveProduct(token, product) {
    const session = validateSession(token);
    if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

    const lock = LockService.getScriptLock();
    try {
        lock.waitLock(10000); // Tunggu antrean maks 10 detik

        const ss = SpreadsheetApp.getActiveSpreadsheet();
        const sheet = ss.getSheetByName('Products');
        if (!sheet) return { success: false, message: "Sheet Products tidak ditemukan." };

        const range = sheet.getDataRange();
        const values = range.getValues();

        if (product.id) {
            // Operasi Edit Produk
            for (let i = 1; i < values.length; i++) {
                if (parseInt(values[i][0]) === product.id) {
                    const rowNum = i + 1;
                    sheet.getRange(rowNum, 2).setValue(product.name);
                    sheet.getRange(rowNum, 3).setValue(product.price);
                    sheet.getRange(rowNum, 4).setValue(product.category);
                    sheet.getRange(rowNum, 5).setValue(product.stock);
                    sheet.getRange(rowNum, 6).setValue(product.emoji);

                    logAction(session.username, "EDIT_PRODUCT", "Memperbarui produk ID: " + product.id + " - " + product.name);
                    return { success: true };
                }
            }
            return { success: false, message: "Produk tidak ditemukan." };
        } else {
            // Operasi Tambah Produk Baru
            let maxId = 0;
            for (let i = 1; i < values.length; i++) {
                const currentId = parseInt(values[i][0]);
                if (currentId > maxId) maxId = currentId;
            }
            const newId = maxId + 1;
            sheet.appendRow([newId, product.name, product.price, product.category, product.stock, product.emoji]);

            logAction(session.username, "ADD_PRODUCT", "Menambahkan produk baru ID: " + newId + " - " + product.name);
            return { success: true };
        }

    } catch (e) {
        return { success: false, message: "Terjadi gangguan server (Lock Busy): " + e.message };
    } finally {
        lock.releaseLock();
    }
}

/**
 * Menghapus Produk dari Inventaris (Lock Service Enabled)
 */
function deleteProduct(token, productId) {
    const session = validateSession(token);
    if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

    const lock = LockService.getScriptLock();
    try {
        lock.waitLock(10000);

        const ss = SpreadsheetApp.getActiveSpreadsheet();
        const sheet = ss.getSheetByName('Products');
        if (!sheet) return { success: false, message: "Sheet Products tidak ditemukan." };

        const values = sheet.getDataRange().getValues();
        for (let i = 1; i < values.length; i++) {
            if (parseInt(values[i][0]) === productId) {
                const productName = values[i][1];
                sheet.deleteRow(i + 1);

                logAction(session.username, "DELETE_PRODUCT", "Menghapus produk ID: " + productId + " - " + productName);
                return { success: true };
            }
        }
        return { success: false, message: "ID produk tidak valid." };

    } catch (e) {
        return { success: false, message: "Server sibuk: " + e.message };
    } finally {
        lock.releaseLock();
    }
}

/**
 * Menyimpan Penjualan Baru & Memotong Stok Produk secara Transaksional (Lock Service Enabled)
 */
function processTransaction(token, trx) {
    const session = validateSession(token);
    if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

    const lock = LockService.getScriptLock();
    try {
        lock.waitLock(15000); // Beri waktu antrean hingga 15 detik untuk transaksi checkout

        const ss = SpreadsheetApp.getActiveSpreadsheet();
        const pSheet = ss.getSheetByName('Products');
        const txSheet = ss.getSheetByName('Transactions');

        if (!pSheet || !txSheet) return { success: false, message: "Konfigurasi spreadsheet tidak lengkap." };

        // 1. Validasi kecukupan stok produk terlebih dahulu sebelum menulis transaksi apapun
        const pValues = pSheet.getDataRange().getValues();
        for (let item of trx.items) {
            let isProductFound = false;
            for (let i = 1; i < pValues.length; i++) {
                if (parseInt(pValues[i][0]) === item.id) {
                    isProductFound = true;
                    const currentStock = parseInt(pValues[i][4]);
                    if (currentStock !== -1 && currentStock < item.quantity) {
                        return { success: false, message: "Kalkulasi Gagal. Stok produk " + item.name + " tidak mencukupi." };
                    }
                    break;
                }
            }
            if (!isProductFound) {
                return { success: false, message: "Produk " + item.name + " tidak lagi terdaftar." };
            }
        }

        // 2. Eksekusi pemotongan stok pada tabel Products (Kecuali Jasa / -1)
        for (let item of trx.items) {
            for (let i = 1; i < pValues.length; i++) {
                if (parseInt(pValues[i][0]) === item.id) {
                    const rowNum = i + 1;
                    const currentStock = parseInt(pValues[i][4]);
                    if (currentStock !== -1) {
                        pSheet.getRange(rowNum, 5).setValue(currentStock - item.quantity);
                    }
                    break;
                }
            }
        }

        // 3. Catat detail transaksi ke tabel Transactions
        txSheet.appendRow([
            trx.id,
            trx.date,
            JSON.stringify(trx.items),
            trx.values.subtotal,
            trx.values.discountPercent,
            trx.values.discountAmount,
            trx.values.taxAmount,
            trx.values.grandTotal,
            trx.method,
            trx.cashPaid,
            trx.change
        ]);

        logAction(session.username, "PROCESS_TRANSACTION", "Checkout penjualan baru ID: " + trx.id + " senilai " + trx.values.grandTotal);
        return { success: true };

    } catch (e) {
        return { success: false, message: "Antrean checkout padat, silakan coba lagi: " + e.message };
    } finally {
        lock.releaseLock();
    }
}

/**
 * Memproses Faktur Pembelian Supplier & Penambahan Stok Produk (Lock Service Enabled)
 */
function submitStockInInvoice(token, invoice) {
    const session = validateSession(token);
    if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

    const lock = LockService.getScriptLock();
    try {
        lock.waitLock(15000);

        const ss = SpreadsheetApp.getActiveSpreadsheet();
        const pSheet = ss.getSheetByName('Products');
        const stSheet = ss.getSheetByName('StockIn');

        if (!pSheet || !stSheet) return { success: false, message: "Sheet Products atau StockIn tidak dikonfigurasi." };

        const pValues = pSheet.getDataRange().getValues();

        // 1. Eksekusi penambahan stok pada sheet Products (Kecuali Jasa / -1)
        for (let item of invoice.items) {
            for (let i = 1; i < pValues.length; i++) {
                if (parseInt(pValues[i][0]) === item.id) {
                    const rowNum = i + 1;
                    const currentStock = parseInt(pValues[i][4]);
                    if (currentStock !== -1) {
                        pSheet.getRange(rowNum, 5).setValue(currentStock + item.quantity);
                    }
                    break;
                }
            }
        }

        // 2. Tambah Log Faktur Stok Masuk
        const now = new Date();
        const formattedDate = now.toLocaleString('id-ID', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
        stSheet.appendRow([
            invoice.id,
            formattedDate,
            invoice.supplier,
            JSON.stringify(invoice.items),
            invoice.totalCost
        ]);

        logAction(session.username, "SUBMIT_STOCK_IN", "Faktur Masuk ID: " + invoice.id + " Supplier: " + invoice.supplier + " senilai: " + invoice.totalCost);
        return { success: true };

    } catch (e) {
        return { success: false, message: "Sistem sibuk memproses antrean stok: " + e.message };
    } finally {
        lock.releaseLock();
    }
}

/**
 * Handle HTTP POST requests from frontend (Vercel)
 */
function doPost(e) {
    try {
        // Karena frontend mengirim sebagai text/plain, datanya ada di e.postData.contents
        const payload = JSON.parse(e.postData.contents);
        const action = payload.action;
        const params = payload.params || [];
        
        // Pastikan fungsi yang diminta ada (this merujuk ke global context)
        if (typeof this[action] === 'function') {
            const result = this[action].apply(this, params);
            return ContentService.createTextOutput(JSON.stringify({
                status: 'success',
                result: result
            })).setMimeType(ContentService.MimeType.JSON);
        } else {
            return ContentService.createTextOutput(JSON.stringify({
                error: 'Function ' + action + ' not found.'
            })).setMimeType(ContentService.MimeType.JSON);
        }
    } catch (error) {
        return ContentService.createTextOutput(JSON.stringify({
            error: error.message
        })).setMimeType(ContentService.MimeType.JSON);
    }
}